### ISSUE TITLE
Make URLs that take you straight to the balance page for specific accounts

### ISSUE THREAD

**Issue by mightybyte** [kadena-community/kadena-tools#3]
One thing I think would be nice is if the balance checker gets the account that it is checking from the URL (i.e. ?account=alice). Then, when you click the "Check Balance" button it updates the URL. That way all account balances would have links that people could paste.

**Comment by LynxLead** [comment]
Done - https://github.com/kadena-community/kadena-tools/pull/5/commits/45f40e2c05fc6f23cef36012aacb7a2d2c085ade
