### ISSUE TITLE
Getting "Validation failed for hash.." Error when Using cross-chain Tool

### ISSUE THREAD

**Issue by yousefjnm** [kadena-community/kadena-tools#7]
Hey,

Thank you for this cool tool.

I am getting this error.

```
Validation failed for hash "py_gi-Mwkwgl7H_6sUXg0n5om4auUV5jp8KFrISWw2Q": Transaction gas price (0.000000000001) is below minimum gas price (0.00000001)
```

I understand that my transaction does not have the minimum gas, how can I fix that?
Did I just lose all my coins?

**Comment by alber70g** [comment]
You didn't loose your coins. You can use https://tools.kadena.io/transactions/cross-chain-transfer-finisher as the cross chain transfer finisher
